### POST request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Jack Frost",
  "email": "jack.frost@gmail.com",
  "address": "123 main Street, London",
  "dateOfBirth": "1996-12-09",
  "registeredDate": "2024-04-01"
}

###