### POST request to create a new patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Jack Frost API Gateway test",
  "email": "jack.frostAPIGatewayTest1@gmail.com",
  "address": "123 main Street, London",
  "dateOfBirth": "1996-12-26",
  "registeredDate": "2024-04-01"
}

###